
spring.r2dbc:
  username: postgres
  password: root
  url: r2dbc:postgresql://localhost:5432/postgres
  repositories.enabled: true

  pool:
    enabled: true
    initial-size: 10
    max-idle-time: 1m
    max-size: 30

server:
  port: 8081

management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api

cbr:
  url: "https://cbr.ru/scripts/XML_daily.asp"




