###
POST https://api.telegram.org/bot5274095592:AAG3dGQeLDE5_JnOH05WbPqjFEdk8b3JWOQ/getUpdates
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "offset": 30
}

###
POST https://api.telegram.org/bot5274095592:AAG3dGQeLDE5_JnOH05WbPqjFEdk8b3JWOQ/sendMessage
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

{
  "chat_id": "1163778484",
  "text": "testOk2",
  "reply_to_message_id": "2"
}
###############################################
